// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ethereum/go-ethereum/consensus/clique (interfaces: ContractClient)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	big "math/big"
	reflect "reflect"

	common "github.com/ethereum/go-ethereum/common"
	consensus "github.com/ethereum/go-ethereum/consensus"
	ctypes "github.com/ethereum/go-ethereum/consensus/clique/ctypes"
	core "github.com/ethereum/go-ethereum/core"
	state "github.com/ethereum/go-ethereum/core/state"
	types "github.com/ethereum/go-ethereum/core/types"
	gomock "github.com/golang/mock/gomock"
)

// MockContractClient is a mock of ContractClient interface.
type MockContractClient struct {
	ctrl     *gomock.Controller
	recorder *MockContractClientMockRecorder
}

// MockContractClientMockRecorder is the mock recorder for MockContractClient.
type MockContractClientMockRecorder struct {
	mock *MockContractClient
}

// NewMockContractClient creates a new mock instance.
func NewMockContractClient(ctrl *gomock.Controller) *MockContractClient {
	mock := &MockContractClient{ctrl: ctrl}
	mock.recorder = &MockContractClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContractClient) EXPECT() *MockContractClientMockRecorder {
	return m.recorder
}

// CommitSpan mocks base method.
func (m *MockContractClient) CommitSpan(arg0 common.Address, arg1 *state.StateDB, arg2 *types.Header, arg3 core.ChainContext, arg4 *[]*types.Transaction, arg5 *[]*types.Receipt, arg6 *[]*types.Transaction, arg7 *uint64, arg8 bool, arg9 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitSpan", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitSpan indicates an expected call of CommitSpan.
func (mr *MockContractClientMockRecorder) CommitSpan(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitSpan", reflect.TypeOf((*MockContractClient)(nil).CommitSpan), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9)
}

// DistributeToValidator mocks base method.
func (m *MockContractClient) DistributeToValidator(arg0 common.Address, arg1 *big.Int, arg2 common.Address, arg3 *state.StateDB, arg4 *types.Header, arg5 core.ChainContext, arg6 *[]*types.Transaction, arg7 *[]*types.Receipt, arg8 *[]*types.Transaction, arg9 *uint64, arg10 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DistributeToValidator", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
	ret0, _ := ret[0].(error)
	return ret0
}

// DistributeToValidator indicates an expected call of DistributeToValidator.
func (mr *MockContractClientMockRecorder) DistributeToValidator(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DistributeToValidator", reflect.TypeOf((*MockContractClient)(nil).DistributeToValidator), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
}

// GetCurrentSpan mocks base method.
func (m *MockContractClient) GetCurrentSpan(arg0 context.Context, arg1 *types.Header) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentSpan", arg0, arg1)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentSpan indicates an expected call of GetCurrentSpan.
func (mr *MockContractClientMockRecorder) GetCurrentSpan(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentSpan", reflect.TypeOf((*MockContractClient)(nil).GetCurrentSpan), arg0, arg1)
}

// GetCurrentValidators mocks base method.
func (m *MockContractClient) GetCurrentValidators(arg0 common.Hash, arg1 *big.Int) ([]*ctypes.Validator, *ctypes.SystemContracts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentValidators", arg0, arg1)
	ret0, _ := ret[0].([]*ctypes.Validator)
	ret1, _ := ret[1].(*ctypes.SystemContracts)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCurrentValidators indicates an expected call of GetCurrentValidators.
func (mr *MockContractClientMockRecorder) GetCurrentValidators(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentValidators", reflect.TypeOf((*MockContractClient)(nil).GetCurrentValidators), arg0, arg1)
}

// GetCurrentValidatorsWithSuperNode mocks base method.
func (m *MockContractClient) GetCurrentValidatorsWithSuperNode(arg0 common.Hash, arg1 *big.Int) ([]*ctypes.Validator, *ctypes.SystemContracts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentValidatorsWithSuperNode", arg0, arg1)
	ret0, _ := ret[0].([]*ctypes.Validator)
	ret1, _ := ret[1].(*ctypes.SystemContracts)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCurrentValidatorsWithSuperNode indicates an expected call of GetCurrentValidatorsWithSuperNode.
func (mr *MockContractClientMockRecorder) GetCurrentValidatorsWithSuperNode(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentValidatorsWithSuperNode", reflect.TypeOf((*MockContractClient)(nil).GetCurrentValidatorsWithSuperNode), arg0, arg1)
}

// GetEligibleValidators mocks base method.
func (m *MockContractClient) GetEligibleValidators(arg0 common.Hash, arg1 uint64) ([]*ctypes.Validator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEligibleValidators", arg0, arg1)
	ret0, _ := ret[0].([]*ctypes.Validator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEligibleValidators indicates an expected call of GetEligibleValidators.
func (mr *MockContractClientMockRecorder) GetEligibleValidators(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEligibleValidators", reflect.TypeOf((*MockContractClient)(nil).GetEligibleValidators), arg0, arg1)
}

// GetKKUB mocks base method.
func (m *MockContractClient) GetKKUB(arg0 context.Context, arg1 *types.Header, arg2 common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKKUB", arg0, arg1, arg2)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKKUB indicates an expected call of GetKKUB.
func (mr *MockContractClientMockRecorder) GetKKUB(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKKUB", reflect.TypeOf((*MockContractClient)(nil).GetKKUB), arg0, arg1, arg2)
}

// GetNftContract mocks base method.
func (m *MockContractClient) GetNftContract(arg0 context.Context, arg1 *types.Header, arg2 common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNftContract", arg0, arg1, arg2)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNftContract indicates an expected call of GetNftContract.
func (mr *MockContractClientMockRecorder) GetNftContract(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNftContract", reflect.TypeOf((*MockContractClient)(nil).GetNftContract), arg0, arg1, arg2)
}

// GetSlashEpochSize mocks base method.
func (m *MockContractClient) GetSlashEpochSize(arg0 context.Context, arg1 *types.Header, arg2 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlashEpochSize", arg0, arg1, arg2)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlashEpochSize indicates an expected call of GetSlashEpochSize.
func (mr *MockContractClientMockRecorder) GetSlashEpochSize(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlashEpochSize", reflect.TypeOf((*MockContractClient)(nil).GetSlashEpochSize), arg0, arg1, arg2)
}

// GetSlashThreshold mocks base method.
func (m *MockContractClient) GetSlashThreshold(arg0 context.Context, arg1 *types.Header, arg2 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSlashThreshold", arg0, arg1, arg2)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSlashThreshold indicates an expected call of GetSlashThreshold.
func (mr *MockContractClientMockRecorder) GetSlashThreshold(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSlashThreshold", reflect.TypeOf((*MockContractClient)(nil).GetSlashThreshold), arg0, arg1, arg2)
}

// GetSoloSlashRate mocks base method.
func (m *MockContractClient) GetSoloSlashRate(arg0 context.Context, arg1 *types.Header, arg2 common.Address) (*big.Int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSoloSlashRate", arg0, arg1, arg2)
	ret0, _ := ret[0].(*big.Int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSoloSlashRate indicates an expected call of GetSoloSlashRate.
func (mr *MockContractClientMockRecorder) GetSoloSlashRate(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSoloSlashRate", reflect.TypeOf((*MockContractClient)(nil).GetSoloSlashRate), arg0, arg1, arg2)
}

// GetStakeManagerStorage mocks base method.
func (m *MockContractClient) GetStakeManagerStorage(arg0 context.Context, arg1 *types.Header) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStakeManagerStorage", arg0, arg1)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStakeManagerStorage indicates an expected call of GetStakeManagerStorage.
func (mr *MockContractClientMockRecorder) GetStakeManagerStorage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStakeManagerStorage", reflect.TypeOf((*MockContractClient)(nil).GetStakeManagerStorage), arg0, arg1)
}

// GetStakeManagerVault mocks base method.
func (m *MockContractClient) GetStakeManagerVault(arg0 context.Context, arg1 *types.Header, arg2 common.Address) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStakeManagerVault", arg0, arg1, arg2)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStakeManagerVault indicates an expected call of GetStakeManagerVault.
func (mr *MockContractClientMockRecorder) GetStakeManagerVault(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStakeManagerVault", reflect.TypeOf((*MockContractClient)(nil).GetStakeManagerVault), arg0, arg1, arg2)
}

// GetValidatorInfoValidatorShareContractByIndex mocks base method.
func (m *MockContractClient) GetValidatorInfoValidatorShareContractByIndex(arg0 context.Context, arg1 *types.Header, arg2 common.Address, arg3 *big.Int) (common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorInfoValidatorShareContractByIndex", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorInfoValidatorShareContractByIndex indicates an expected call of GetValidatorInfoValidatorShareContractByIndex.
func (mr *MockContractClientMockRecorder) GetValidatorInfoValidatorShareContractByIndex(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorInfoValidatorShareContractByIndex", reflect.TypeOf((*MockContractClient)(nil).GetValidatorInfoValidatorShareContractByIndex), arg0, arg1, arg2, arg3)
}

// InitialSuperNode mocks base method.
func (m *MockContractClient) InitialSuperNode(arg0 common.Address, arg1 uint64, arg2 common.Address, arg3 *state.StateDB, arg4 *types.Header, arg5 core.ChainContext, arg6 *[]*types.Transaction, arg7 *[]*types.Receipt, arg8 *[]*types.Transaction, arg9 *uint64, arg10 bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitialSuperNode", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
	ret0, _ := ret[0].(error)
	return ret0
}

// InitialSuperNode indicates an expected call of InitialSuperNode.
func (mr *MockContractClientMockRecorder) InitialSuperNode(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitialSuperNode", reflect.TypeOf((*MockContractClient)(nil).InitialSuperNode), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10)
}

// Inject mocks base method.
func (m *MockContractClient) Inject(arg0 common.Address, arg1 ctypes.SignerTxFn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Inject", arg0, arg1)
}

// Inject indicates an expected call of Inject.
func (mr *MockContractClientMockRecorder) Inject(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inject", reflect.TypeOf((*MockContractClient)(nil).Inject), arg0, arg1)
}

// IsSlashed mocks base method.
func (m *MockContractClient) IsSlashed(arg0 common.Address, arg1 consensus.ChainHeaderReader, arg2 common.Address, arg3 *big.Int, arg4 *types.Header) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSlashed", arg0, arg1, arg2, arg3, arg4)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSlashed indicates an expected call of IsSlashed.
func (mr *MockContractClientMockRecorder) IsSlashed(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSlashed", reflect.TypeOf((*MockContractClient)(nil).IsSlashed), arg0, arg1, arg2, arg3, arg4)
}

// SetBKCValidatorAddress mocks base method.
func (m *MockContractClient) SetBKCValidatorAddress(arg0 common.Address) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBKCValidatorAddress", arg0)
}

// SetBKCValidatorAddress indicates an expected call of SetBKCValidatorAddress.
func (mr *MockContractClientMockRecorder) SetBKCValidatorAddress(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBKCValidatorAddress", reflect.TypeOf((*MockContractClient)(nil).SetBKCValidatorAddress), arg0)
}

// SetSigner mocks base method.
func (m *MockContractClient) SetSigner(arg0 types.Signer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSigner", arg0)
}

// SetSigner indicates an expected call of SetSigner.
func (mr *MockContractClientMockRecorder) SetSigner(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSigner", reflect.TypeOf((*MockContractClient)(nil).SetSigner), arg0)
}

// Slash mocks base method.
func (m *MockContractClient) Slash(arg0, arg1 common.Address, arg2 consensus.ChainHeaderReader, arg3 *state.StateDB, arg4 *types.Header, arg5 core.ChainContext, arg6 *[]*types.Transaction, arg7 *[]*types.Receipt, arg8 *[]*types.Transaction, arg9 *uint64, arg10 bool, arg11 *big.Int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Slash", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11)
	ret0, _ := ret[0].(error)
	return ret0
}

// Slash indicates an expected call of Slash.
func (mr *MockContractClientMockRecorder) Slash(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Slash", reflect.TypeOf((*MockContractClient)(nil).Slash), arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11)
}
